[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG = "info"

[unstable]
build-std = ["core", "alloc"]

[build]
target = "xtensa-esp32-none-elf"
